/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_get
  (JNIEnv *, jclass);

/*
 * Class:     HelloJNI
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_set
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
